name: training999
description: "a Flee Bullet Game."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flame: 1.18.0
  flame_tiled: 1.20.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.14.1
  flame_riverpod: 5.4.0
  flutter_riverpod: 2.5.1
  riverpod_annotation: 2.3.4
  freezed: 2.5.2
  freezed_annotation: 2.4.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_crashlytics: ^4.2.0
  firebase_analytics: ^11.3.6
  hooks_riverpod: ^2.5.2
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: 3.0.0
  riverpod_generator: 2.3.11

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  background_color_ios: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true